# Generated by Django 3.0.7 on 2020-06-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_mailinglist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingList',
            new_name='NewsletterUser',
        ),
    ]
